# Generated by Django 4.2.16 on 2024-10-02 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img_base64',
            field=models.TextField(blank=True),
        ),
    ]
